GENRE_NAME_MAX_LENGTH = 200

BOOK_TITLE_MAX_LENGTH = 200
BOOK_SUMMARY_MAX_LENGTH = 200
BOOK_ISBN_MAX_LENGTH = 200

BOOK_INSTANCE_IMPRINT_MAX_LENGTH = 200
BOOK_INSTANCE_STATUS_MAX_LENGTH = 1
BOOK_INSTANCE_LOAN_STATUS = (
    ('m', 'Maintenance'),
    ('o', 'On loan'),
    ('a', 'Available'),
    ('r', 'Reserved'),
)

AUTHOR_FIRST_NAME_MAX_LENGTH = 100
AUTHOR_LAST_NAME_MAX_LENGTH = 100
